// Every composition the studio can render. Eleven of them, in three groups, in the order a
// newcomer should meet them:
//
//   START HERE            one composition that proves the install
//   GENERIC TEMPLATES     the reusable ones. Each has a plan file you edit; none needs a key,
//                         an API or an asset you have to go and find
//   CURATED EXAMPLES      finished pieces kept because each demonstrates something the generic
//                         templates do not
//
// Every one of them renders from a clean clone, and none needs a step that spends money.
//
// ⚠️ No composition here writes its duration or its dimensions as a bare number where the template
// can derive them. A number typed twice is a number that can disagree with itself.

import { Composition } from "remotion";
import { CodeWalkthrough } from "./CodeWalkthrough";

import { AiTop5Composition, TOTAL_FRAMES as AI_TOP5_TOTAL_FRAMES } from "./templates/ai_top5";
import {
  BrandSting,
  calculateMetadata as brandStingCalculateMetadata,
  BRAND_STING_DEFAULT,
} from "./templates/brand_sting";
import {
  NarrativeArc,
  calculateMetadata as narrativeArcCalculateMetadata,
  NARRATIVE_ARC_DEFAULT,
} from "./templates/narrative_arc";
import { LogoShowcase, LOGO_SHOWCASE_FRAMES } from "./templates/solvx_logo";
import { HelloWorld, HELLO_WORLD_FRAMES } from "./templates/hello_world";
import { ProductWalkthrough, PRODUCT_WALKTHROUGH_FRAMES } from "./templates/product_walkthrough";
import { FootagePromo, FOOTAGE_PROMO_FRAMES } from "./templates/footage_promo";
import { SlotShort, SLOT_SHORT_FRAMES } from "./templates/slot_short";
import { StepSequence, STEP_SEQUENCE_FRAMES } from "./templates/step_sequence";
import {
  VerticalAdvert,
  VERTICAL_ADVERT_FRAMES,
  calculateMetadata as verticalAdvertCalculateMetadata,
} from "./templates/vertical_advert";
import { calculateMetadata } from "./calculate-metadata/calculate-metadata";
import { schema } from "./calculate-metadata/schema";

export const RemotionRoot = () => {
  return (
    <>
      {/* ══ START HERE ═══════════════════════════════════════════════════════════════════════ */}

      {/* No API key, no public/ assets, no web font, no audio — so this renders from a clean
          clone on a machine with nothing configured. It is both the install proof
          (npm run hello) and the template to copy when you start a real piece. */}
      <Composition
        id="HelloWorld"
        component={HelloWorld}
        fps={30}
        width={1920}
        height={1080}
        durationInFrames={HELLO_WORLD_FRAMES}
        defaultProps={{}}
      />

      {/* ══ GENERIC TEMPLATES ════════════════════════════════════════════════════════════════
          Every one of these renders from a clean clone. Edit the plan file named in each note;
          the duration is derived from that plan, never typed here. */}

      {/* A caption-led tour of a product interface, driven by a virtual camera over one still
          capture. The sample interface is drawn in DOM, so there are no assets to fetch.
          Edit templates/product_walkthrough/stages.ts to retarget it. */}
      <Composition
        id="ProductWalkthrough"
        component={ProductWalkthrough}
        fps={30}
        width={1920}
        height={1080}
        durationInFrames={PRODUCT_WALKTHROUGH_FRAMES}
        defaultProps={{}}
      />

      {/* A footage-led promo cut to a musical grid. Sections are bars, cuts are beats, and every
          frame number is derived from the BPM. The two sample clips and the voice-band
          placeholders are generated by scripts/make-footage-samples.mjs; the bed and SFX are the
          in-house synthesized set. Edit templates/footage_promo/plan.ts. */}
      <Composition
        id="FootagePromo"
        component={FootagePromo}
        fps={30}
        width={1920}
        height={1080}
        durationInFrames={FOOTAGE_PROMO_FRAMES}
        defaultProps={{}}
      />

      {/* A short promo or explainer assembled from ordered content slots, where the order is
          EDITORIAL — shuffle the middle and nobody is confused. Brand tokens in, slots in order,
          timing derived from the plan. The brand mark is drawn from the name when no logo is
          supplied. Edit templates/slot_short/plan.ts. */}
      <Composition
        id="SlotShort"
        component={SlotShort}
        fps={30}
        width={1920}
        height={1080}
        durationInFrames={SLOT_SHORT_FRAMES}
        defaultProps={{}}
      />

      {/* Ordered steps in a process, where the order is CAUSAL — step 3 follows step 2 because it
          has to. That is the whole distinction from SlotShort, and the persistent rail is what
          makes it visible: the viewer always knows which step this is and how many are left.
          Edit templates/step_sequence/plan.ts. */}
      <Composition
        id="StepSequence"
        component={StepSequence}
        fps={30}
        width={1920}
        height={1080}
        durationInFrames={STEP_SEQUENCE_FRAMES}
        defaultProps={{ showRail: true }}
      />

      {/* A short-form social advert. Text is confined to a safe rectangle so the platform's own
          interface cannot cover it; footage is reframed to fill the frame. Edit
          templates/vertical_advert/plan.ts. Pass showSafeGuides to see the reserved zones.

          ⚠️ ONE registration, two shapes. The format prop drives calculateMetadata, so the
          dimensions come from the template's own FORMAT_SIZE table rather than being typed here:

            npx remotion render VerticalAdvert out/advert.mp4                          -> 1080x1920
            npx remotion render VerticalAdvert out/a.mp4 --props='{"format":"16x9"}'   -> 1920x1080

          This replaces a second `VerticalAdvertLandscape` entry that duplicated the component and
          hand-wrote the landscape size beside it. */}
      <Composition
        id="VerticalAdvert"
        component={VerticalAdvert}
        fps={30}
        width={1080}
        height={1920}
        durationInFrames={VERTICAL_ADVERT_FRAMES}
        calculateMetadata={verticalAdvertCalculateMetadata}
        defaultProps={{ format: "9x16" as const, showSafeGuides: false }}
      />

      {/* ══ CURATED EXAMPLES ═════════════════════════════════════════════════════════════════
          Finished pieces, kept because each teaches something the generic templates do not. */}

      {/* The repo's original system: Code Hike + Twoslash token-level transitions over the
          public/code*.* files. The one composition here that measures the DOM before rendering
          (delayRender / continueRender), which is why it is worth reading. */}
      <Composition
        id="CodeWalkthrough"
        component={CodeWalkthrough}
        defaultProps={{
          steps: null,
          themeColors: null,
          theme: "github-dark" as const,
          codeWidth: null,
          width: {
            type: "auto",
          },
        }}
        fps={30}
        height={1080}
        calculateMetadata={calculateMetadata}
        schema={schema}
      />

      {/* An emotional-arc structure — setup, turn, payoff — expressed as a config of beats. */}
      <Composition
        id="NarrativeArc"
        component={NarrativeArc}
        fps={30}
        width={1920}
        height={1080}
        durationInFrames={NARRATIVE_ARC_DEFAULT.beats.reduce((n, b) => n + Math.round(b.dur_s * 30), 0)}
        calculateMetadata={narrativeArcCalculateMetadata}
        defaultProps={{ config: NARRATIVE_ARC_DEFAULT }}
      />

      {/* A short branded reveal built from a scraped BrandPack — colours and marks as data. */}
      <Composition
        id="BrandSting"
        component={BrandSting}
        fps={30}
        width={1920}
        height={1080}
        durationInFrames={BRAND_STING_DEFAULT.total_frames}
        calculateMetadata={brandStingCalculateMetadata}
        defaultProps={{ config: BRAND_STING_DEFAULT }}
      />

      {/* A recolourable vector wordmark: 21 colourway presets of ONE mark, plus a live recolour.
          Vector-crisp at any size because the colours are props, not baked pixels. */}
      <Composition
        id="LogoShowcase"
        component={LogoShowcase}
        fps={30}
        width={1920}
        height={1080}
        durationInFrames={LOGO_SHOWCASE_FRAMES}
        defaultProps={{}}
      />

      {/* A data-driven daily edition: a ranked countdown from #5 to #1, each story on the screen of
          a different era's television, with the energy escalating toward #1. It is here because it
          is a materially different kind of piece from the templates above — a SHOW with a running
          order, a music bed it is cut to, and an edition's worth of copy as data.

          Its sample edition lives in templates/ai_top5/data.ts and is deliberately SILENT: no
          redistributable, licence-clean voice set was available, so rather than name mp3s that do
          not exist the shipped edition has real nulls and is designed to read without narration.
          The voiced path still works — a regenerated edition populates the VO fields and the
          section lengths follow the measured clips.

          The whole timeline is derived in templates/ai_top5/grid.ts from a 124 BPM musical grid,
          in exact beat space. `node scripts/check-ai-top5-grid.mjs` measures its drift. */}
      <Composition
        id="AiTop5"
        component={AiTop5Composition}
        fps={30}
        width={1920}
        height={1080}
        durationInFrames={AI_TOP5_TOTAL_FRAMES}
        defaultProps={{}}
      />

    </>
  );
};
