import { useRef } from 'react';
import { useNavigate } from 'react-router-dom';
import { driver, type DriveStep } from 'driver.js';
import 'driver.js/dist/driver.css';
import { projectsApi, slotsApi } from '../api';

function waitForElement(selector: string, timeout = 4000): Promise<Element | null> {
  return new Promise(resolve => {
    const deadline = Date.now() + timeout;
    const check = () => {
      const el = document.querySelector(selector);
      if (el) { resolve(el); return; }
      if (Date.now() > deadline) { resolve(null); return; }
      setTimeout(check, 100);
    };
    check();
  });
}

function scrollTo(selector: string): Promise<void> {
  return waitForElement(selector).then(el => {
    el?.scrollIntoView({ behavior: 'smooth', block: 'center' });
    return new Promise(r => setTimeout(r, 400));
  });
}

function delay(ms: number): Promise<void> {
  return new Promise(r => setTimeout(r, ms));
}

// Step copy — separated from nav logic so it's easy to edit
const STEPS: Array<{ title: string; description: string }> = [
  // 0
  {
    title: 'Welcome to Video Bright',
    description:
      'Video Bright is an end-to-end production pipeline for AI-powered video campaigns. Every asset — still frame or video clip — flows through a structured brief → generation → approval workflow. Nothing gets lost, nothing gets regenerated twice, and nothing gets sent to an AI model without a sign-off.',
  },
  // 1
  {
    title: 'Projects at a glance',
    description:
      'Each project maps to one campaign. Status, slot completion, and total estimated AI generation cost are visible before you even open it — a producer can triage a full slate of campaigns in under a minute.',
  },
  // 2
  {
    title: 'The production workspace',
    description:
      'This is where a campaign is built and managed. Brief editors, creative directors, and AI generation all share one project — no email chains, no Slack threads, no disconnected tools. Every change is versioned and timestamped. Every decision is auditable.',
  },
  // 3
  {
    title: 'Project control panel',
    description:
      'The sidebar holds project status, team assignments, and workflow gating. When the creative team is done, one click submits the project for manager review. When a manager approves, AI generation is unlocked. Nobody generates anything without a sign-off first.',
  },
  // 4
  {
    title: 'Total cost — before you spend a penny',
    description:
      'Every AI generation has a known, deterministic cost. The estimated total is calculated from your slot configuration before a single token is sent to a model. Actual spend appears here as jobs run, so you always know exactly what was spent and on what — with a per-slot breakdown.',
  },
  // 5
  {
    title: 'Timeline and storyboard views',
    description:
      'Switch between the Timeline — where you drag clips, set target durations, and define in/out trim points — and the Storyboard grid, which shows all slots at once with current asset thumbnails. Both views are live: changes save instantly, no save button needed.',
  },
  // 6
  {
    title: 'The Timeline editor',
    description:
      'Drag the right edge of any clip to adjust its target duration. The change saves to the server in real time. Trim in/out points for captured assets are set per-slot in the panel on the right. The timeline is your production schedule and your edit decision list in one place — update it and the render picks up the change automatically.',
  },
  // 7
  {
    title: 'The creative brief',
    description:
      'Every slot starts with a brief — headline, description, and production notes. The brief feeds directly into the AI prompt builder and is what reviewers check before approving. A well-written brief produces better generation results and keeps the whole team aligned on creative intent. It\'s the single source of truth for each scene.',
  },
  // 8
  {
    title: 'Source mode and AI provider',
    description:
      'A slot can be sourced manually — you upload the asset — or generated by AI. When set to Generated, choose the provider: Gemini Image for stills, Veo Lite for video, with more models as the platform grows. Provider selection is per-slot, so you can mix and match models in the same campaign.',
  },
  // 9
  {
    title: 'Prompt & Generate',
    description:
      'This opens the full prompt-construction page — structured fields for subject, setting, lighting, camera angle, and style compile into a final prompt with a live preview. Aspect ratio, reference images (up to 3), and a cost estimate are all set before you commit. You always know exactly what you\'re asking the model to do before you spend anything.',
  },
  // 10
  {
    title: 'The generation page',
    description:
      'Structured prompt fields, aspect ratio selector, reference image drop zones, and a cost estimate — all on one page before you click Generate. For still slots this is Gemini Image; for video it\'s Veo. Same workflow, same cost transparency, different model. Every run is versioned automatically.',
  },
  // 11
  {
    title: 'Generation history',
    description:
      'Every generation run is saved automatically — the model used, the exact prompt, the cost incurred, the result thumbnail, and the attempt number. Select any previous run to make it the active asset without re-generating. Versioning is built in: you never lose a result you already paid for, and you can always roll back.',
  },
  // 12
  {
    title: 'Assets',
    description:
      'Assets accepted into a slot flow straight into the render pipeline. Upload manually, pull from the media library, or accept an AI generation — the workflow is the same either way. The links here navigate directly to Brand Assets and the Media Library with this slot pre-selected for a seamless import.',
  },
  // 13
  {
    title: 'Brand Assets library',
    description:
      'Logos, product shots, approved brand photography — all in one place, shared across the whole team. Any asset can be imported directly into a slot. Upload once, use across every project. Nobody has to hunt through Dropbox folders or ask the designer for the latest logo version.',
  },
  // 14
  {
    title: 'Media Library',
    description:
      'The media library holds ingested footage — web captures, sourced clips, reference material. Browse, preview, and import into any slot without leaving the app. No more downloading assets to your desktop and re-uploading them somewhere else.',
  },
  // 15
  {
    title: 'Render pipeline',
    description:
      'When all slots have accepted assets, hit Generate Preview or Generate Final. The render engine stitches clips and stills in sequence, respects trim points and fit modes, and produces an MP4. Preview renders are fast and low-res for quick sign-off; final renders go to delivery quality. Both are tracked here with timestamps and status.',
  },
  // 16
  {
    title: 'Slot review and approval',
    description:
      'Submit a slot for review and a manager is notified. They can approve, reject with comments, or request specific changes. Nothing moves to final render without a completed approval chain. Every comment and decision is preserved in the project audit trail — no more guessing what was agreed.',
  },
  // 17
  {
    title: 'Project-level workflow',
    description:
      'Submit the whole project for generation approval with one click. The status progresses: Draft → Ready for Review → Approved for Generation → In Production → Complete. At each stage the right people are gated in — editors build, managers approve, nobody jumps ahead.',
  },
  // 18
  {
    title: 'God-mode developer access',
    description:
      'The ⚡ Dev button — visible to super-admins only — opens a live SQL console and system diagnostics. Developers can inspect the database, run queries, and debug the platform in production without a separate tool. It\'s invisible to all other roles — clients and creators never see it.',
  },
  // 19
  {
    title: "That's Video Bright",
    description:
      'A complete AI video production pipeline in one place: structured briefing, multi-model AI generation, per-frame cost visibility, editorial timeline control, team review and approval, brand asset management, and final render delivery. This is the platform your campaign deserves.',
  },
];

export function DemoTour() {
  const navigate = useNavigate();
  const driverRef = useRef<ReturnType<typeof driver> | null>(null);

  async function startTour() {
    if (driverRef.current) {
      driverRef.current.destroy();
      driverRef.current = null;
    }

    // Pre-load __DEMO__ project and its slots
    const projects = await projectsApi.list().catch(() => []);
    const demoProject = projects.find((p: any) => p.title === '__DEMO__') ?? projects[0];
    const projectId = demoProject?.id as number | undefined;
    const demoSlots = projectId
      ? await slotsApi.list(projectId).catch(() => [])
      : [];
    const heroSlot = (demoSlots as any[]).find((s: any) => s.source_mode === 'generated') ?? demoSlots[0];
    const heroSlotId = (heroSlot as any)?.id as number | undefined;

    // Start on project list
    navigate('/projects');
    await waitForElement('[data-demo="project-list"]');
    await delay(300);

    let d: ReturnType<typeof driver>;

    function makeStep(
      index: number,
      element: string,
      side: 'top' | 'bottom' | 'left' | 'right' = 'bottom',
      handler?: () => void,
    ): DriveStep {
      return {
        element,
        popover: {
          title: STEPS[index].title,
          description: STEPS[index].description,
          side,
          align: 'center',
          ...(handler ? { onNextClick: handler } : {}),
        },
      };
    }

    const steps: DriveStep[] = [
      // 0 — project list: next → move to step 1 (project-card, same page)
      makeStep(0, '[data-demo="project-list"]', 'bottom', () => {
        d.moveNext();
      }),

      // 1 — project card: next → navigate into the demo project
      makeStep(1, '[data-demo="project-card"]', 'right', () => {
        if (!projectId) { d.moveNext(); return; }
        navigate(`/projects/${projectId}`);
        waitForElement('[data-demo="project-header"]', 5000).then(() => {
          delay(300).then(() => d.moveNext());
        });
      }),

      // 2 — project header
      makeStep(2, '[data-demo="project-header"]', 'bottom', () => {
        scrollTo('[data-demo="project-sidebar"]').then(() => d.moveNext());
      }),

      // 3 — sidebar
      makeStep(3, '[data-demo="project-sidebar"]', 'right', () => {
        scrollTo('[data-demo="sidebar-costs"]').then(() => d.moveNext());
      }),

      // 4 — costs
      makeStep(4, '[data-demo="sidebar-costs"]', 'right', () => {
        // Ensure timeline view is active and scroll to view toggle
        scrollTo('[data-demo="view-toggle"]').then(() => d.moveNext());
      }),

      // 5 — view toggle
      makeStep(5, '[data-demo="view-toggle"]', 'bottom', () => {
        // Click the timeline button if it exists
        const btns = document.querySelectorAll('[data-demo="view-toggle"] button');
        const timelineBtn = Array.from(btns).find(b => b.textContent?.includes('Timeline')) as HTMLElement | null;
        timelineBtn?.click();
        waitForElement('[data-demo="timeline-editor"]', 3000).then(() => {
          delay(200).then(() => d.moveNext());
        });
      }),

      // 6 — timeline editor: next → click HERO slot to open panel
      makeStep(6, '[data-demo="timeline-editor"]', 'bottom', () => {
        const selector = heroSlotId
          ? `[data-demo="timeline-editor"] [data-slot-id="${heroSlotId}"]`
          : '[data-demo="timeline-editor"] [data-slot-id]';
        const slotBlock = document.querySelector(selector) as HTMLElement | null;
        if (slotBlock) {
          slotBlock.click();
        } else {
          const card = document.querySelector('[data-demo="slot-card"]') as HTMLElement | null;
          card?.click();
        }
        waitForElement('[data-demo="slot-brief"]', 4000).then(() => {
          delay(300).then(() => d.moveNext());
        });
      }),

      // 7 — slot brief
      makeStep(7, '[data-demo="slot-brief"]', 'left', () => {
        scrollTo('[data-demo="slot-source"]').then(() => d.moveNext());
      }),

      // 8 — slot source
      makeStep(8, '[data-demo="slot-source"]', 'left', () => {
        scrollTo('[data-demo="slot-generation"]').then(() => d.moveNext());
      }),

      // 9 — generation button: next → navigate to video-generate for HERO slot
      makeStep(9, '[data-demo="slot-generation"]', 'left', () => {
        if (!projectId) { d.moveNext(); return; }
        if (heroSlotId) {
          navigate(`/projects/${projectId}/video-generate?slot=${heroSlotId}`);
        } else {
          navigate(`/projects/${projectId}`);
        }
        delay(600).then(() => d.moveNext());
      }),

      // 10 — video generate page (no specific element — highlight body)
      makeStep(10, 'body', 'bottom', () => {
        if (!projectId) { d.moveNext(); return; }
        navigate(`/projects/${projectId}`);
        // Re-open the HERO slot to show history
        waitForElement('[data-demo="timeline-editor"]', 5000).then(async () => {
          await delay(400);
          const selector = heroSlotId
            ? `[data-demo="timeline-editor"] [data-slot-id="${heroSlotId}"]`
            : '[data-demo="timeline-editor"] [data-slot-id]';
          const slotBlock = document.querySelector(selector) as HTMLElement | null;
          if (slotBlock) {
            slotBlock.click();
          } else {
            const card = document.querySelector('[data-demo="slot-card"]') as HTMLElement | null;
            card?.click();
          }
          await waitForElement('[data-demo="slot-history"]', 4000);
          await scrollTo('[data-demo="slot-history"]');
          d.moveNext();
        });
      }),

      // 11 — history
      makeStep(11, '[data-demo="slot-history"]', 'left', () => {
        scrollTo('[data-demo="slot-assets"]').then(() => d.moveNext());
      }),

      // 12 — assets: next → brand assets page
      makeStep(12, '[data-demo="slot-assets"]', 'left', () => {
        navigate('/brand-assets');
        waitForElement('[data-demo="brand-assets-page"]', 5000).then(() => {
          delay(300).then(() => d.moveNext());
        });
      }),

      // 13 — brand assets page: next → media library
      makeStep(13, '[data-demo="brand-assets-page"]', 'bottom', () => {
        navigate('/media-library');
        waitForElement('[data-demo="media-library-page"]', 5000).then(() => {
          delay(300).then(() => d.moveNext());
        });
      }),

      // 14 — media library: next → back to project, scroll to render panel
      makeStep(14, '[data-demo="media-library-page"]', 'bottom', () => {
        if (!projectId) { d.moveNext(); return; }
        navigate(`/projects/${projectId}`);
        waitForElement('[data-demo="render-panel"]', 5000).then(async () => {
          await delay(400);
          await scrollTo('[data-demo="render-panel"]');
          d.moveNext();
        });
      }),

      // 15 — render panel
      makeStep(15, '[data-demo="render-panel"]', 'top', () => {
        // Re-open HERO slot to show review section
        const selector = heroSlotId
          ? `[data-demo="timeline-editor"] [data-slot-id="${heroSlotId}"]`
          : '[data-demo="timeline-editor"] [data-slot-id]';
        const slotBlock = document.querySelector(selector) as HTMLElement | null;
        const card = document.querySelector('[data-demo="slot-card"]') as HTMLElement | null;
        if (slotBlock) slotBlock.click();
        else if (card) card.click();

        waitForElement('[data-demo="slot-review"]', 3000).then(el => {
          if (el) {
            scrollTo('[data-demo="slot-review"]').then(() => d.moveNext());
          } else {
            d.moveNext();
          }
        });
      }),

      // 16 — review section (may not be visible for all roles — fallback to sidebar-actions)
      makeStep(16, '[data-demo="slot-review"]', 'left', () => {
        scrollTo('[data-demo="sidebar-actions"]').then(() => d.moveNext());
      }),

      // 17 — sidebar actions
      makeStep(17, '[data-demo="sidebar-actions"]', 'right', () => {
        scrollTo('[data-demo="project-header"]').then(() => d.moveNext());
      }),

      // 18 — project header / dev button: just advance (stay on project page)
      makeStep(18, '[data-demo="project-header"]', 'bottom', () => {
        navigate('/projects');
        waitForElement('[data-demo="project-list"]', 4000).then(() => {
          delay(300).then(() => d.moveNext());
        });
      }),

      // 19 — final step on project list
      makeStep(19, '[data-demo="project-list"]', 'bottom'),
    ];

    d = driver({
      animate: true,
      smoothScroll: true,
      allowClose: true,
      showProgress: true,
      progressText: '{{current}} of {{total}}',
      nextBtnText: 'Next →',
      prevBtnText: '← Back',
      doneBtnText: 'Done',
      popoverClass: 'vb-demo-popover',
      steps,
      onDestroyStarted: () => {
        d.destroy();
        driverRef.current = null;
      },
    });

    driverRef.current = d;

    // Step 0 is on project-list — skip the duplicate step 1 by adjusting start
    // We drive from step 0; step 1 (project-card) is only reached if user clicks Back from step 2
    d.drive(0);
  }

  return (
    <button
      onClick={startTour}
      className="text-xs font-medium px-3 py-1.5 rounded bg-indigo-700 hover:bg-indigo-600
        text-white transition-colors shadow-lg"
    >
      Demo
    </button>
  );
}
